from typing import Protocol


class DeliveryRepository(Protocol):
    def list_deliveries(self) -> list[dict]: ...
    def get_delivery(self, delivery_id: str) -> dict | None: ...
    def save_delivery(self, delivery_id: str, data: dict) -> None: ...
    def next_seq(self) -> int: ...
    def get_run_transcript(self, delivery_id: str, run_id: str) -> dict | None: ...
    def save_run_transcript(self, delivery_id: str, run_id: str, data: dict) -> None: ...
