from typing import Protocol


class IssueRepository(Protocol):
    def list_issues(self) -> list[dict]: ...
    def get_issue(self, issue_id: str) -> dict | None: ...
    def save_issue(self, issue_id: str, data: dict) -> None: ...
    def get_run_transcript(self, issue_id: str, run_id: str) -> dict | None: ...
    def save_run_transcript(self, issue_id: str, run_id: str, data: dict) -> None: ...
