from pathlib import Path
from typing import Protocol


class RuleRepository(Protocol):
    def list_rules(self) -> list[dict]: ...
    def get_rule(self, category: str, name: str) -> dict | None: ...
    def save_rule(self, category: str, name: str, content: str) -> None: ...
    def delete_rule(self, category: str, name: str) -> bool: ...
    def import_from(self, source_dir: Path) -> list[str]: ...
