from pathlib import Path
from typing import Protocol


class SkillRepository(Protocol):
    def list_skills(self) -> list[dict]: ...
    def get_skill(self, skill_id: str) -> dict | None: ...
    def save_skill(self, skill_id: str, content: str) -> None: ...
    def delete_skill(self, skill_id: str) -> bool: ...
    def import_from(self, source_dir: Path) -> list[str]: ...
