from typing import Protocol


class SourceRepository(Protocol):
    def list_sources(self) -> list[dict]: ...
    def get_source(self, source_id: str) -> dict | None: ...
    def save_source(self, source_id: str, data: dict) -> None: ...
    def delete_source(self, source_id: str) -> bool: ...
