from typing import Protocol

from app.domain.models.delivery import DeliveryCreate, DeliveryUpdate


class DeliveryUseCases(Protocol):
    def list_deliveries(self) -> list[dict]: ...
    def get_delivery(self, delivery_id: str) -> dict | None: ...
    def create_delivery(self, body: DeliveryCreate) -> dict: ...
    def update_delivery(self, delivery_id: str, body: DeliveryUpdate) -> dict | None: ...
    def close_delivery(self, delivery_id: str) -> dict | None: ...
    def approve(self, delivery_id: str) -> dict | None: ...
    def reject(self, delivery_id: str, reason: str) -> dict | None: ...
    def retry(self, delivery_id: str) -> dict | None: ...
    def cancel(self, delivery_id: str) -> dict | None: ...
    def advance_from_intake(self, delivery_id: str) -> dict | None: ...
    def get_run_transcript(self, delivery_id: str, run_id: str) -> dict | None: ...
    def save_run_transcript(self, delivery_id: str, run_id: str, data: dict) -> None: ...
    def get_stream_log(self, delivery_id: str, run_id: str) -> dict | None: ...
    def collect_session(self, delivery_id: str, session_id: str) -> dict | None: ...
    async def generate_plan(self, delivery_id: str) -> dict | None: ...
    async def run_implement(self, delivery_id: str) -> dict | None: ...
    async def run_review(self, delivery_id: str) -> dict | None: ...
    async def auto_trigger_phase(self, delivery_id: str) -> dict | None: ...
