from typing import Protocol

from app.domain.models.delivery import DeliveryCreate, DeliveryUpdate


class DeliveryUseCases(Protocol):
    def list_deliveries(self) -> list[dict]: ...
    def get_delivery(self, delivery_id: str) -> dict | None: ...
    def create_delivery(self, body: DeliveryCreate) -> dict: ...
    def update_delivery(self, delivery_id: str, body: DeliveryUpdate) -> dict | None: ...
    def get_run_transcript(self, delivery_id: str, run_id: str) -> dict | None: ...
    def save_run_transcript(self, delivery_id: str, run_id: str, data: dict) -> None: ...
    def collect_session(self, delivery_id: str, session_id: str) -> dict | None: ...
