from typing import Protocol

from app.domain.models.issue import IssueCreate, IssueUpdate


class IssueUseCases(Protocol):
    def list_issues(self) -> list[dict]: ...
    def get_issue(self, issue_id: str) -> dict | None: ...
    def create_issue(self, body: IssueCreate) -> dict: ...
    def update_issue(self, issue_id: str, body: IssueUpdate) -> dict | None: ...
    def get_run_transcript(self, issue_id: str, run_id: str) -> dict | None: ...
    def save_run_transcript(self, issue_id: str, run_id: str, data: dict) -> None: ...
    def collect_session(self, issue_id: str, session_id: str) -> dict | None: ...
