from typing import Protocol

from app.domain.models.source import SourceCreate, SourceUpdate


class SourceUseCases(Protocol):
    def list_sources(self) -> list[dict]: ...
    def get_source(self, source_id: str) -> dict | None: ...
    def create_source(self, body: SourceCreate) -> dict: ...
    def update_source(self, source_id: str, body: SourceUpdate) -> dict | None: ...
    def delete_source(self, source_id: str) -> bool: ...
